package gg.thronebound.dockyard.registry

import gg.thronebound.dockyard.registry.registries.ChickenVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object ChickenVariants {
    val COLD = ChickenVariantRegistry["minecraft:cold"]
    val TEMPERATE = ChickenVariantRegistry["minecraft:temperate"]
    val WARM = ChickenVariantRegistry["minecraft:warm"]
}
