package gg.thronebound.dockyard.registry

import gg.thronebound.dockyard.registry.registries.PigVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object PigVariants {
    val COLD = PigVariantRegistry["minecraft:cold"]
    val TEMPERATE = PigVariantRegistry["minecraft:temperate"]
    val WARM = PigVariantRegistry["minecraft:warm"]
}
