package gg.thronebound.dockyard.registry

import gg.thronebound.dockyard.registry.registries.WolfSoundVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object WolfSoundVariants {
    val ANGRY = WolfSoundVariantRegistry["minecraft:angry"]
    val BIG = WolfSoundVariantRegistry["minecraft:big"]
    val CLASSIC = WolfSoundVariantRegistry["minecraft:classic"]
    val CUTE = WolfSoundVariantRegistry["minecraft:cute"]
    val GRUMPY = WolfSoundVariantRegistry["minecraft:grumpy"]
    val PUGLIN = WolfSoundVariantRegistry["minecraft:puglin"]
    val SAD = WolfSoundVariantRegistry["minecraft:sad"]
}
